# Generated by Skyramp v1.3.30 on 2026-06-29 23:48:17.720898016 +0000 UTC m=+453.230583578
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/deployments/{id}/create_flow_run \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=c8e5a3b4-7f2d-4e91-b6a0-3d5c8f941abc \
# 		--provider \
# 		--request-data {"name":"test-flow-run-404","parameters":{},"tags":[]} \
# 		--response-status-code 404 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/deployments/{id}/create_flow_run POST
def test_create_flow_run_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "c8e5a3b4-7f2d-4e91-b6a0-3d5c8f941abc"

    # Request Body
    create_flow_run_POST_request_body = r'''{
        "name": "test-flow-run-404",
        "parameters": {},
        "tags": []
    }'''

    # Execute Request
    create_flow_run_POST_response = client.send_request(
        url=URL,
        path="/api/deployments/{id}/create_flow_run",
        method="POST",
        body=create_flow_run_POST_request_body,
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert create_flow_run_POST_response.status_code == 404
    assert skyramp.get_response_value(create_flow_run_POST_response, "detail") == "Deployment not found"


if __name__ == "__main__":
    test_create_flow_run_post()
