# Generated by Skyramp v1.3.30 on 2026-06-29 23:46:46.00401328 +0000 UTC m=+549.857736855
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/deployments/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output deployments_POST_missing_work_pool_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"test-deployment-missing-pool","flow_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6"} \
# 		--response-status-code 422 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/deployments/ POST
def test_deployments_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    deployments_POST_request_body = r'''{
        "flow_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "name": "test-deployment-missing-pool"
    }'''

    # Execute Request
    deployments_POST_response = client.send_request(
        url=URL,
        path="/api/deployments/",
        method="POST",
        body=deployments_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert deployments_POST_response.status_code == 422
    assert skyramp.get_response_value(deployments_POST_response, "exception_detail.0.type") == "missing"
    assert skyramp.get_response_value(deployments_POST_response, "exception_detail.0.msg") == "Field required"
    assert skyramp.get_response_value(deployments_POST_response, "exception_detail.1") is None


if __name__ == "__main__":
    test_deployments_post()
