# Generated by Skyramp v1.3.30 on 2026-06-29 23:47:14.533037729 +0000 UTC m=+578.386761325
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output deployment_create_with_work_pool_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_deployment-create-with-work-pool.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_ = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    deployments = "6ba7b810-9dad-11d1-80b4-00c04fd430c8"

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "test-flow-work-pool-1"
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body
    )

    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "name") == "test-flow-work-pool-1"
    assert skyramp.get_response_value(endpoint_2_POST_response, "id") is not None
    flow_id = skyramp.get_response_value(endpoint_2_POST_response, "id")

    # Request Body
    endpoint_3_POST_request_body = r'''{
        "name": "test-pool-work-pool-1",
        "type": "process"
    }'''

    # Execute Request
    endpoint_3_POST_response = client.send_request(
        url=URL_,
        path="/api/work_pools/",
        method="POST",
        body=endpoint_3_POST_request_body
    )

    # Generated Assertions
    assert endpoint_3_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_3_POST_response, "name") == "test-pool-work-pool-1"
    assert skyramp.get_response_value(endpoint_3_POST_response, "type") == "process"
    assert skyramp.get_response_value(endpoint_3_POST_response, "id") is not None

    # Request Body
    import json as _json
    endpoint_1_POST_request_body = _json.dumps({
        "flow_id": flow_id,
        "name": "test-deployment-work-pool-1",
        "work_pool_name": "test-pool-work-pool-1"
    })

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_,
        path="/api/deployments/",
        method="POST",
        body=endpoint_1_POST_request_body
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "test-deployment-work-pool-1"
    assert skyramp.get_response_value(endpoint_1_POST_response, "work_pool_name") == "test-pool-work-pool-1"
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None

    # Execute Request
    deployments_GET_response = client.send_request(
        url=URL_,
        path="/api/deployments/{deployments}",
        method="GET",
        path_params={"deployments": deployments}
    )

    # Generated Assertions
    assert deployments_GET_response.status_code == 200
    assert skyramp.get_response_value(deployments_GET_response, "name") == "test-deployment-work-pool-1"
    assert skyramp.get_response_value(deployments_GET_response, "work_pool_name") == "test-pool-work-pool-1"
    assert skyramp.get_response_value(deployments_GET_response, "id") == skyramp.get_response_value(endpoint_1_POST_response, "id")


if __name__ == "__main__":
    test_integration()
