# Generated by Skyramp v1.3.30 on 2026-06-29 23:48:30.522891518 +0000 UTC m=+466.032577090
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output deployment_flow_run_job_id_verification_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_deployment-flow-run-job-id-verification.json

# Import of required libraries
import skyramp
import os
import re
import time


# URL for test requests
URL_ = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    deployments = "e5f6a7b8-9012-34ef-ab01-e5f6a7b89012"
    flow_runs = "f6a7b8c9-0123-45fa-b012-f6a7b8c90123"

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "test-flow-job-verify-1751000000"
    }'''

    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body
    )

    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_2_POST_response, "name") == "test-flow-job-verify-1751000000"
    assert re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', skyramp.get_response_value(endpoint_2_POST_response, "id"), re.IGNORECASE)

    # Request Body — flow_id chained from step 1 response
    flow_id = skyramp.get_response_value(endpoint_2_POST_response, "id")
    endpoint_1_POST_request_body = f'{{"flow_id": "{flow_id}", "name": "test-deploy-job-verify-1751000000"}}'

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_,
        path="/api/deployments/",
        method="POST",
        body=endpoint_1_POST_request_body
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "test-deploy-job-verify-1751000000"
    assert re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', skyramp.get_response_value(endpoint_1_POST_response, "id"), re.IGNORECASE)

    # Request Body — deployment_id chained from step 2 response
    deployment_id = skyramp.get_response_value(endpoint_1_POST_response, "id")
    create_flow_run_POST_request_body = r'''{
        "name": "test-flow-run-verify-1751000000",
        "parameters": {},
        "tags": []
    }'''

    # Execute Request
    create_flow_run_POST_response = client.send_request(
        url=URL_,
        path="/api/deployments/{deployments}/create_flow_run",
        method="POST",
        body=create_flow_run_POST_request_body,
        path_params={"deployments": deployment_id}
    )

    # Generated Assertions
    assert create_flow_run_POST_response.status_code == 202
    assert re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', skyramp.get_response_value(create_flow_run_POST_response, "job_id"), re.IGNORECASE)

    # Execute Request — job_id chained from step 3 response
    job_id = skyramp.get_response_value(create_flow_run_POST_response, "job_id")
    flow_runs_GET_response = client.send_request(
        url=URL_,
        path="/api/flow_runs/{flow_runs}",
        method="GET",
        path_params={"flow_runs": job_id}
    )

    # Generated Assertions
    assert flow_runs_GET_response.status_code == 200
    assert skyramp.get_response_value(flow_runs_GET_response, "id") == skyramp.get_response_value(create_flow_run_POST_response, "job_id")
    assert skyramp.get_response_value(flow_runs_GET_response, "state.type") == "SCHEDULED"
    assert re.match(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', skyramp.get_response_value(flow_runs_GET_response, "deployment_id"), re.IGNORECASE)


if __name__ == "__main__":
    test_integration()
