# Generated by Skyramp v1.3.30 on 2026-06-29 23:47:32.608608235 +0000 UTC m=+396.886929130
# Command: skyramp generate contract rest http://localhost:4200/api/work_queues/{id}/status \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=a1b2c3d4-e5f6-7890-abcd-ef1234567890 \
# 		--provider \
# 		--response-data {"health":{"is_healthy":false,"last_poll_time":null},"runs":{"late_count":0}} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/work_queues/{id}/status GET
def test_status_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"

    # Setup: create a work queue to test against
    setup_response = client.send_request(
        url=URL,
        path="/api/work_queues/",
        method="POST",
        headers=headers,
        body='{"name": "status-contract-wq"}'
    )
    assert setup_response.status_code == 201
    id = skyramp.get_response_value(setup_response, "id")
    assert id is not None

    # Expected Response Body
    expected_status_GET_response_body = r'''{
        "health": {
            "is_healthy": false,
            "last_poll_time": null
        },
        "runs": {
            "late_count": 0
        }
    }'''

    # Execute Request
    status_GET_response = client.send_request(
        url=URL,
        path="/api/work_queues/{id}/status",
        method="GET",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert status_GET_response.status_code == 200
    assert skyramp.check_schema(status_GET_response, expected_status_GET_response_body)
    assert skyramp.get_response_value(status_GET_response, "health.is_healthy") == False
    assert skyramp.get_response_value(status_GET_response, "health.last_poll_time") is None
    assert skyramp.get_response_value(status_GET_response, "runs.late_count") == 0
    assert skyramp.get_response_value(status_GET_response, "runs.late_count") >= 0


if __name__ == "__main__":
    test_status_get()
