# Generated by Skyramp v1.3.30 on 2026-06-29 23:45:30.195274236 +0000 UTC m=+461.621925936
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/work_queues/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output work_queues_POST_default_description_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"test-wq-no-desc"} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/work_queues/ POST
def test_work_queues_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    work_queues_POST_request_body = r'''{
        "name": "test-wq-no-desc"
    }'''

    # Execute Request
    work_queues_POST_response = client.send_request(
        url=URL,
        path="/api/work_queues/",
        method="POST",
        body=work_queues_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert work_queues_POST_response.status_code == 201
    assert skyramp.get_response_value(work_queues_POST_response, "name") == "test-wq-no-desc"
    assert skyramp.get_response_value(work_queues_POST_response, "description") == ""
    assert skyramp.get_response_value(work_queues_POST_response, "is_paused") == False
    assert skyramp.get_response_value(work_queues_POST_response, "priority") >= 1
    assert skyramp.get_response_value(work_queues_POST_response, "concurrency_limit") is None
    assert skyramp.get_response_value(work_queues_POST_response, "id") is not None


if __name__ == "__main__":
    test_work_queues_post()
