# Generated by Skyramp v1.3.30 on 2026-06-29 23:36:15.339124988 +0000 UTC m=+399.749499523
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output work_queue_duplicate_name_conflict_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_work-queue-duplicate-name-conflict.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_ = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "description": "First queue",
        "is_paused": false,
        "name": "dup-work-queue-1751183000"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_,
        path="/api/work_queues/",
        method="POST",
        body=endpoint_1_POST_request_body
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "dup-work-queue-1751183000"
    assert skyramp.get_response_value(endpoint_1_POST_response, "description") == "First queue"
    assert skyramp.get_response_value(endpoint_1_POST_response, "is_paused") == False
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "created") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "updated") is not None

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "description": "Duplicate queue",
        "is_paused": false,
        "name": "dup-work-queue-1751183000"
    }'''

    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_,
        path="/api/work_queues/",
        method="POST",
        body=endpoint_1_POST_1_request_body
    )

    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 409
    assert skyramp.get_response_value(endpoint_1_POST_1_response, "detail") == "A work queue with this name already exists."


if __name__ == "__main__":
    test_integration()
