# Generated by Skyramp v1.3.30 on 2026-06-29 23:46:57.549148616 +0000 UTC m=+497.161096619
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output work_queue_description_create_verify_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_work-queue-description-create-verify.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_ = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    work_queues = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "description": "My integration test work queue description",
        "name": "wq-integration-desc-test"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_,
        path="/api/work_queues/",
        method="POST",
        body=endpoint_1_POST_request_body
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "wq-integration-desc-test"
    assert skyramp.get_response_value(endpoint_1_POST_response, "description") == "My integration test work queue description"
    assert skyramp.get_response_value(endpoint_1_POST_response, "is_paused") == False
    assert skyramp.get_response_value(endpoint_1_POST_response, "priority") >= 1
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    assert len(skyramp.get_response_value(endpoint_1_POST_response, "id")) == 36
    assert skyramp.get_response_value(endpoint_1_POST_response, "created") is not None
    work_queues = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Execute Request
    work_queues_GET_response = client.send_request(
        url=URL_,
        path="/api/work_queues/{work_queues}",
        method="GET",
        path_params={"work_queues": work_queues}
    )

    # Generated Assertions
    assert work_queues_GET_response.status_code == 200
    assert skyramp.get_response_value(work_queues_GET_response, "id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(work_queues_GET_response, "name") == "wq-integration-desc-test"
    assert skyramp.get_response_value(work_queues_GET_response, "description") == "My integration test work queue description"
    assert skyramp.get_response_value(work_queues_GET_response, "is_paused") == False


if __name__ == "__main__":
    test_integration()
