# Generated by Skyramp v1.3.30 on 2026-06-29 23:45:44.359559245 +0000 UTC m=+475.786210955
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output work_queue_create_max_description_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_work-queue-create-max-description.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_ = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "description": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "name": "test-wq-max-desc"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_,
        path="/api/work_queues/",
        method="POST",
        body=endpoint_1_POST_request_body
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "test-wq-max-desc"
    assert skyramp.get_response_value(endpoint_1_POST_response, "description") == "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    assert skyramp.get_response_value(endpoint_1_POST_response, "is_paused") == False
    assert skyramp.get_response_value(endpoint_1_POST_response, "priority") >= 1
    assert skyramp.get_response_value(endpoint_1_POST_response, "concurrency_limit") is None
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None

    # Execute Request
    work_queues_GET_response = client.send_request(
        url=URL_,
        path="/api/work_queues/{work_queues}",
        method="GET",
        path_params={"work_queues": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )

    # Generated Assertions
    assert work_queues_GET_response.status_code == 200
    assert skyramp.get_response_value(work_queues_GET_response, "id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(work_queues_GET_response, "name") == "test-wq-max-desc"
    assert skyramp.get_response_value(work_queues_GET_response, "description") == "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    assert skyramp.get_response_value(work_queues_GET_response, "is_paused") == False
    assert skyramp.get_response_value(work_queues_GET_response, "priority") >= 1


if __name__ == "__main__":
    test_integration()
