# Generated by Skyramp v1.3.30 on 2026-06-29 23:48:01.116660363 +0000 UTC m=+425.394981278
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output work_queue_status_healthy_after_poll_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_work-queue-status-healthy-after-poll.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    work_queues = None

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "healthy-poll-wq-1"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/work_queues/",
        method="POST",
        body=endpoint_1_POST_request_body
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "healthy-poll-wq-1"
    assert skyramp.get_response_value(endpoint_1_POST_response, "status") == "NOT_READY"
    work_queues = skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert work_queues is not None

    # Request Body
    work_queues_PATCH_request_body = r'''{
        "last_polled": "2026-06-29T12:00:00+00:00"
    }'''

    # Execute Request
    work_queues_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/work_queues/{work_queues}",
        method="PATCH",
        body=work_queues_PATCH_request_body,
        path_params={"work_queues": work_queues}
    )

    # Generated Assertions
    assert work_queues_PATCH_response.status_code == 204

    # Execute Request
    status_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/work_queues/{work_queues}/status",
        method="GET",
        path_params={"work_queues": work_queues}
    )

    # Generated Assertions
    assert status_GET_response.status_code == 200
    assert skyramp.get_response_value(status_GET_response, "health.is_healthy") == True
    assert skyramp.get_response_value(status_GET_response, "health.last_poll_time") is not None
    assert skyramp.get_response_value(status_GET_response, "runs.late_count") == 0
    assert skyramp.get_response_value(status_GET_response, "runs.late_count") >= 0


if __name__ == "__main__":
    test_integration()
