# Generated by Skyramp v1.3.30 on 2026-06-29 23:46:32.61607828 +0000 UTC m=+472.228026277
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/work_queues/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output work_queues_POST_description_too_long_provider_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"name":"wq-test-long-description","description":"This description is intentionally exceeding the maximum length of one hundred characters as required for testing the new max_length validation constraint added to WorkQueueCreate"} \
# 		--response-status-code 422 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/work_queues/ POST
def test_work_queues_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    work_queues_POST_request_body = r'''{
        "description": "This description is intentionally exceeding the maximum length of one hundred characters as required for testing the new max_length validation constraint added to WorkQueueCreate",
        "name": "wq-test-long-description"
    }'''

    # Execute Request
    work_queues_POST_response = client.send_request(
        url=URL,
        path="/api/work_queues/",
        method="POST",
        body=work_queues_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert work_queues_POST_response.status_code == 422
    assert skyramp.get_response_value(work_queues_POST_response, "exception_message") == "Invalid request received."
    assert skyramp.get_response_value(work_queues_POST_response, "exception_detail.0.type") == "string_too_long"
    assert skyramp.get_response_value(work_queues_POST_response, "exception_detail.0.loc.1") == "description"
    assert skyramp.get_response_value(work_queues_POST_response, "exception_detail.0.msg") == "String should have at most 100 characters"
    assert skyramp.get_response_value(work_queues_POST_response, "exception_detail.0.ctx.max_length") == 100
    assert skyramp.get_response_value(work_queues_POST_response, "exception_detail.1") is None


if __name__ == "__main__":
    test_work_queues_post()
