# Generated by Skyramp v1.3.30 on 2026-06-29 23:36:12.860391738 +0000 UTC m=+397.270766274
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output work_queue_create_read_update_lifecycle_integration_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_work-queue-create-read-update-lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_ = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "description": "Integration test queue",
        "is_paused": false,
        "name": "test-work-queue-1751183000"
    }'''

    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_,
        path="/api/work_queues/",
        method="POST",
        body=endpoint_1_POST_request_body
    )

    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201
    assert skyramp.get_response_value(endpoint_1_POST_response, "name") == "test-work-queue-1751183000"
    assert skyramp.get_response_value(endpoint_1_POST_response, "description") == "Integration test queue"
    assert skyramp.get_response_value(endpoint_1_POST_response, "is_paused") == False
    assert skyramp.get_response_value(endpoint_1_POST_response, "id") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "created") is not None
    assert skyramp.get_response_value(endpoint_1_POST_response, "updated") is not None

    # Chain work queue ID from POST response
    work_queues = skyramp.get_response_value(endpoint_1_POST_response, "id")

    # Execute Request
    work_queues_GET_response = client.send_request(
        url=URL_,
        path="/api/work_queues/{work_queues}",
        method="GET",
        path_params={"work_queues": work_queues}
    )

    # Generated Assertions
    assert work_queues_GET_response.status_code == 200
    assert skyramp.get_response_value(work_queues_GET_response, "id") == skyramp.get_response_value(endpoint_1_POST_response, "id")
    assert skyramp.get_response_value(work_queues_GET_response, "name") == "test-work-queue-1751183000"
    assert skyramp.get_response_value(work_queues_GET_response, "description") == "Integration test queue"
    assert skyramp.get_response_value(work_queues_GET_response, "is_paused") == False

    # Request Body
    work_queues_PATCH_request_body = r'''{
        "description": "Updated description",
        "is_paused": true
    }'''

    # Execute Request
    work_queues_PATCH_response = client.send_request(
        url=URL_,
        path="/api/work_queues/{work_queues}",
        method="PATCH",
        body=work_queues_PATCH_request_body,
        path_params={"work_queues": work_queues}
    )

    # Generated Assertions
    assert work_queues_PATCH_response.status_code == 204


if __name__ == "__main__":
    test_integration()
