# Generated by Skyramp v1.3.30 on 2026-06-29 23:35:53.970844612 +0000 UTC m=+378.381219157
# Command: skyramp generate contract rest http://127.0.0.1:4200/api/work_queues/{id} \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output work_queue_delete_removed_contract_test.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params id=a7c8f3e2-9b4d-4a6f-8c1e-3d5f7b9e0a2c \
# 		--provider \
# 		--response-status-code 405 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://127.0.0.1:4200")

# contract test for /api/work_queues/{id} DELETE
def test_work_queues_id_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    id = "a7c8f3e2-9b4d-4a6f-8c1e-3d5f7b9e0a2c"

    # Execute Request
    work_queues_id_DELETE_response = client.send_request(
        url=URL,
        path="/api/work_queues/{id}",
        method="DELETE",
        headers=headers,
        path_params={"id": id}
    )

    # Generated Assertions
    assert work_queues_id_DELETE_response.status_code == 405
    assert skyramp.get_response_value(work_queues_id_DELETE_response, "detail") == "Method Not Allowed"


if __name__ == "__main__":
    test_work_queues_id_delete()
